### ISSUE TITLE
Video Duration on Thumbnails are 0:00

### ISSUE THREAD

**Issue by helloadib** [edrisranjbar/sammakquran#8]
It happened again, and I don't know why.

**Comment by edrisranjbar** [comment]
we have still problem with this. we should implement the idea of syncing metadata in a better and more efficient way. know after each video being posted; we are calculating media metadata, but we can limit the process to only the new uploaded media. so that it wouldn't take time (probably less than 0.5S).

## TODO:
- [ ] only process the last uploaded media (after publishing that post)
- [ ] we should send a get request and close the connection, so we don't wait for the result and everything will be `asynchronously` handled in the back-end.
